### ISSUE TITLE
Incluir opções de raça Branco, Pardo, Preto, Amarelo, Indígena

### ISSUE THREAD

**Issue by fernandohaddadmoura** [mandatomarina/emandato#17]
Tentei importar uma lista que tinha raça e deu erro.

Favor incluir opções de raça Branco, Pardo, Preto, Amarelo, Indígena

**Comment by pmarkun** [comment]
http://emandato.marinahelou.com.br/admin/cidadaos/raca/ <- aqui você consegue adicionar. mas coloquei lá.
